//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class DynamicInterfaceValuesMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/DynamicInterfaceValues";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public InterfaceValueMsg states;
        public InterfaceValueMsg commands;

        public DynamicInterfaceValuesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.states = new InterfaceValueMsg();
            this.commands = new InterfaceValueMsg();
        }

        public DynamicInterfaceValuesMsg(Std.HeaderMsg header, InterfaceValueMsg states, InterfaceValueMsg commands)
        {
            this.header = header;
            this.states = states;
            this.commands = commands;
        }

        public static DynamicInterfaceValuesMsg Deserialize(MessageDeserializer deserializer) => new DynamicInterfaceValuesMsg(deserializer);

        private DynamicInterfaceValuesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.states = InterfaceValueMsg.Deserialize(deserializer);
            this.commands = InterfaceValueMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.states);
            serializer.Write(this.commands);
        }

        public override string ToString()
        {
            return "DynamicInterfaceValuesMsg: " +
            "\nheader: " + header.ToString() +
            "\nstates: " + states.ToString() +
            "\ncommands: " + commands.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
