//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class JointTrajectoryControllerStateMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/JointTrajectoryControllerState";
        public override string RosMessageName => k_RosMessageName;

        //  This message presents current controller state of JTC
        //  Header timestamp should be update time of controller state
        public Std.HeaderMsg header;
        public string[] joint_names;
        //  The set point, that is, desired state.
        public Trajectory.JointTrajectoryPointMsg reference;
        //  Current value of the process (ie: latest sensor measurement on the controlled value).
        public Trajectory.JointTrajectoryPointMsg feedback;
        //  The error of the controlled value, essentially reference - feedback (for a regular PID implementation).
        public Trajectory.JointTrajectoryPointMsg error;
        //  Current output of the controller.
        public Trajectory.JointTrajectoryPointMsg output;
        public string[] multi_dof_joint_names;
        //  The set point, that is, desired state.
        public Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_reference;
        //  Current value of the process (ie: latest sensor measurement on the controlled value).
        public Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_feedback;
        //  The error of the controlled value, essentially reference - feedback (for a regular PID implementation).
        public Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_error;
        //  Current output of the controller.
        public Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_output;
        //  The speed scaling factor the trajectory is currently being executed with
        public double speed_scaling_factor;

        public JointTrajectoryControllerStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.joint_names = new string[0];
            this.reference = new Trajectory.JointTrajectoryPointMsg();
            this.feedback = new Trajectory.JointTrajectoryPointMsg();
            this.error = new Trajectory.JointTrajectoryPointMsg();
            this.output = new Trajectory.JointTrajectoryPointMsg();
            this.multi_dof_joint_names = new string[0];
            this.multi_dof_reference = new Trajectory.MultiDOFJointTrajectoryPointMsg();
            this.multi_dof_feedback = new Trajectory.MultiDOFJointTrajectoryPointMsg();
            this.multi_dof_error = new Trajectory.MultiDOFJointTrajectoryPointMsg();
            this.multi_dof_output = new Trajectory.MultiDOFJointTrajectoryPointMsg();
            this.speed_scaling_factor = 0.0;
        }

        public JointTrajectoryControllerStateMsg(Std.HeaderMsg header, string[] joint_names, Trajectory.JointTrajectoryPointMsg reference, Trajectory.JointTrajectoryPointMsg feedback, Trajectory.JointTrajectoryPointMsg error, Trajectory.JointTrajectoryPointMsg output, string[] multi_dof_joint_names, Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_reference, Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_feedback, Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_error, Trajectory.MultiDOFJointTrajectoryPointMsg multi_dof_output, double speed_scaling_factor)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.reference = reference;
            this.feedback = feedback;
            this.error = error;
            this.output = output;
            this.multi_dof_joint_names = multi_dof_joint_names;
            this.multi_dof_reference = multi_dof_reference;
            this.multi_dof_feedback = multi_dof_feedback;
            this.multi_dof_error = multi_dof_error;
            this.multi_dof_output = multi_dof_output;
            this.speed_scaling_factor = speed_scaling_factor;
        }

        public static JointTrajectoryControllerStateMsg Deserialize(MessageDeserializer deserializer) => new JointTrajectoryControllerStateMsg(deserializer);

        private JointTrajectoryControllerStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            this.reference = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
            this.feedback = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
            this.error = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
            this.output = Trajectory.JointTrajectoryPointMsg.Deserialize(deserializer);
            deserializer.Read(out this.multi_dof_joint_names, deserializer.ReadLength());
            this.multi_dof_reference = Trajectory.MultiDOFJointTrajectoryPointMsg.Deserialize(deserializer);
            this.multi_dof_feedback = Trajectory.MultiDOFJointTrajectoryPointMsg.Deserialize(deserializer);
            this.multi_dof_error = Trajectory.MultiDOFJointTrajectoryPointMsg.Deserialize(deserializer);
            this.multi_dof_output = Trajectory.MultiDOFJointTrajectoryPointMsg.Deserialize(deserializer);
            deserializer.Read(out this.speed_scaling_factor);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.Write(this.reference);
            serializer.Write(this.feedback);
            serializer.Write(this.error);
            serializer.Write(this.output);
            serializer.WriteLength(this.multi_dof_joint_names);
            serializer.Write(this.multi_dof_joint_names);
            serializer.Write(this.multi_dof_reference);
            serializer.Write(this.multi_dof_feedback);
            serializer.Write(this.multi_dof_error);
            serializer.Write(this.multi_dof_output);
            serializer.Write(this.speed_scaling_factor);
        }

        public override string ToString()
        {
            return "JointTrajectoryControllerStateMsg: " +
            "\nheader: " + header.ToString() +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\nreference: " + reference.ToString() +
            "\nfeedback: " + feedback.ToString() +
            "\nerror: " + error.ToString() +
            "\noutput: " + output.ToString() +
            "\nmulti_dof_joint_names: " + System.String.Join(", ", multi_dof_joint_names.ToList()) +
            "\nmulti_dof_reference: " + multi_dof_reference.ToString() +
            "\nmulti_dof_feedback: " + multi_dof_feedback.ToString() +
            "\nmulti_dof_error: " + multi_dof_error.ToString() +
            "\nmulti_dof_output: " + multi_dof_output.ToString() +
            "\nspeed_scaling_factor: " + speed_scaling_factor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
