//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class MotionArgumentMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/MotionArgument";
        public override string RosMessageName => k_RosMessageName;

        //  Key Value pair to be used in MotionPrimitive messages
        public string name;
        public double value;

        public MotionArgumentMsg()
        {
            this.name = "";
            this.value = 0.0;
        }

        public MotionArgumentMsg(string name, double value)
        {
            this.name = name;
            this.value = value;
        }

        public static MotionArgumentMsg Deserialize(MessageDeserializer deserializer) => new MotionArgumentMsg(deserializer);

        private MotionArgumentMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "MotionArgumentMsg: " +
            "\nname: " + name.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
