//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class MotionPrimitiveSequenceMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/MotionPrimitiveSequence";
        public override string RosMessageName => k_RosMessageName;

        public MotionPrimitiveMsg[] motions;

        public MotionPrimitiveSequenceMsg()
        {
            this.motions = new MotionPrimitiveMsg[0];
        }

        public MotionPrimitiveSequenceMsg(MotionPrimitiveMsg[] motions)
        {
            this.motions = motions;
        }

        public static MotionPrimitiveSequenceMsg Deserialize(MessageDeserializer deserializer) => new MotionPrimitiveSequenceMsg(deserializer);

        private MotionPrimitiveSequenceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motions, MotionPrimitiveMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.motions);
            serializer.Write(this.motions);
        }

        public override string ToString()
        {
            return "MotionPrimitiveSequenceMsg: " +
            "\nmotions: " + System.String.Join(", ", motions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
