//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class MotionPrimitiveMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/MotionPrimitive";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte UNKNOWN = -1;
        public const sbyte LINEAR_JOINT = 0; //  Often referred as PTP
        public const sbyte LINEAR_CARTESIAN = 50; //  Often referred as LIN
        public const sbyte CIRCULAR_CARTESIAN = 51; //  Often referred as CIRC
        //  potentially more, such as spline motion
        public sbyte type = -1; //  one of the above
        public double blend_radius;
        //  MotionArguments are meant to be used as vendor-specific or use-case-specific arguments to
        //  MotionPrimitive messages. This is to avoid bloating the MotionPrimitive message with all possible
        //  uses cases but rather add specific data using as a list of key-value pairs, which is what this
        //  message represents.
        public MotionArgumentMsg[] additional_arguments;
        //  (max) velocity, (max) acceleration, efficiency
        //  Targets should be either specified through joint configurations or Cartesian poses.
        //  Depending on the motion type and implementation, there might be multiple poses allowed.
        //  For example, circular motions are often specified as via and target
        //  Usually one of these is empty, in some edge cases even both can be empty, when all input is given
        //  in the more flexible MotionArgument[] field.
        public Geometry.PoseStampedMsg[] poses;
        public double[] joint_positions;

        public MotionPrimitiveMsg()
        {
            this.blend_radius = 0.0;
            this.additional_arguments = new MotionArgumentMsg[0];
            this.poses = new Geometry.PoseStampedMsg[0];
            this.joint_positions = new double[0];
        }

        public MotionPrimitiveMsg(sbyte type, double blend_radius, MotionArgumentMsg[] additional_arguments, Geometry.PoseStampedMsg[] poses, double[] joint_positions)
        {
            this.type = type;
            this.blend_radius = blend_radius;
            this.additional_arguments = additional_arguments;
            this.poses = poses;
            this.joint_positions = joint_positions;
        }

        public static MotionPrimitiveMsg Deserialize(MessageDeserializer deserializer) => new MotionPrimitiveMsg(deserializer);

        private MotionPrimitiveMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.blend_radius);
            deserializer.Read(out this.additional_arguments, MotionArgumentMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.poses, Geometry.PoseStampedMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.joint_positions, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.blend_radius);
            serializer.WriteLength(this.additional_arguments);
            serializer.Write(this.additional_arguments);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
            serializer.WriteLength(this.joint_positions);
            serializer.Write(this.joint_positions);
        }

        public override string ToString()
        {
            return "MotionPrimitiveMsg: " +
            "\ntype: " + type.ToString() +
            "\nblend_radius: " + blend_radius.ToString() +
            "\nadditional_arguments: " + System.String.Join(", ", additional_arguments.ToList()) +
            "\nposes: " + System.String.Join(", ", poses.ToList()) +
            "\njoint_positions: " + System.String.Join(", ", joint_positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
