//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class SpeedScalingFactorMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/SpeedScalingFactor";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains a scaling factor to scale trajectory execution. A factor of 1.0 means
        //  execution at normal speed, a factor of 0.0 means a full pause.
        //  Negative values are not allowed (Which should be checked by any instance consuming this message).
        public double factor;

        public SpeedScalingFactorMsg()
        {
            this.factor = 0.0;
        }

        public SpeedScalingFactorMsg(double factor)
        {
            this.factor = factor;
        }

        public static SpeedScalingFactorMsg Deserialize(MessageDeserializer deserializer) => new SpeedScalingFactorMsg(deserializer);

        private SpeedScalingFactorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.factor);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.factor);
        }

        public override string ToString()
        {
            return "SpeedScalingFactorMsg: " +
            "\nfactor: " + factor.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
