//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class StateMsg : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/State";
        public override string RosMessageName => k_RosMessageName;

        //  Primary state definitions as depicted in:
        //  http://design.ros2.org/articles/node_lifecycle.html
        //  These are the primary states. State changes can only be requested when the
        //  node is in one of these states.
        //  Indicates state has not yet been set.
        public const byte PRIMARY_STATE_UNKNOWN = 0;
        //  This is the life cycle state the node is in immediately after being
        //  instantiated.
        public const byte PRIMARY_STATE_UNCONFIGURED = 1;
        //  This state represents a node that is not currently performing any processing.
        public const byte PRIMARY_STATE_INACTIVE = 2;
        //  This is the main state of the node's life cycle. While in this state, the node
        //  performs any processing, responds to service requests, reads and processes
        //  data, produces output, etc.
        public const byte PRIMARY_STATE_ACTIVE = 3;
        //  The finalized state is the state in which the node ends immediately before
        //  being destroyed.
        public const byte PRIMARY_STATE_FINALIZED = 4;
        //  Temporary intermediate states. When a transition is requested, the node
        //  changes its state into one of these states.
        //  In this transition state the node's onConfigure callback will be called to
        //  allow the node to load its configuration and conduct any required setup.
        public const byte TRANSITION_STATE_CONFIGURING = 10;
        //  In this transition state the node's callback onCleanup will be called to clear
        //  all state and return the node to a functionally equivalent state as when
        //  first created.
        public const byte TRANSITION_STATE_CLEANINGUP = 11;
        //  In this transition state the callback onShutdown will be executed to do any
        //  cleanup necessary before destruction.
        public const byte TRANSITION_STATE_SHUTTINGDOWN = 12;
        //  In this transition state the callback onActivate will be executed to do any
        //  final preparations to start executing.
        public const byte TRANSITION_STATE_ACTIVATING = 13;
        //  In this transition state the callback onDeactivate will be executed to do any
        //  cleanup to start executing, and reverse the onActivate changes.
        public const byte TRANSITION_STATE_DEACTIVATING = 14;
        //  This transition state is where any error may be cleaned up.
        public const byte TRANSITION_STATE_ERRORPROCESSING = 15;
        //  The state id value from the above definitions.
        public byte id;
        //  A text label of the state.
        public string label;

        public StateMsg()
        {
            this.id = 0;
            this.label = "";
        }

        public StateMsg(byte id, string label)
        {
            this.id = id;
            this.label = label;
        }

        public static StateMsg Deserialize(MessageDeserializer deserializer) => new StateMsg(deserializer);

        private StateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.label);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.label);
        }

        public override string ToString()
        {
            return "StateMsg: " +
            "\nid: " + id.ToString() +
            "\nlabel: " + label.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
