//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class TransitionDescriptionMsg : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/TransitionDescription";
        public override string RosMessageName => k_RosMessageName;

        //  The transition id and label of this description.
        public TransitionMsg transition;
        //  The current state from which this transition transitions.
        public StateMsg start_state;
        //  The desired target state of this transition.
        public StateMsg goal_state;

        public TransitionDescriptionMsg()
        {
            this.transition = new TransitionMsg();
            this.start_state = new StateMsg();
            this.goal_state = new StateMsg();
        }

        public TransitionDescriptionMsg(TransitionMsg transition, StateMsg start_state, StateMsg goal_state)
        {
            this.transition = transition;
            this.start_state = start_state;
            this.goal_state = goal_state;
        }

        public static TransitionDescriptionMsg Deserialize(MessageDeserializer deserializer) => new TransitionDescriptionMsg(deserializer);

        private TransitionDescriptionMsg(MessageDeserializer deserializer)
        {
            this.transition = TransitionMsg.Deserialize(deserializer);
            this.start_state = StateMsg.Deserialize(deserializer);
            this.goal_state = StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.transition);
            serializer.Write(this.start_state);
            serializer.Write(this.goal_state);
        }

        public override string ToString()
        {
            return "TransitionDescriptionMsg: " +
            "\ntransition: " + transition.ToString() +
            "\nstart_state: " + start_state.ToString() +
            "\ngoal_state: " + goal_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
