//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lifecycle
{
    [Serializable]
    public class TransitionEventMsg : Message
    {
        public const string k_RosMessageName = "lifecycle_msgs/TransitionEvent";
        public override string RosMessageName => k_RosMessageName;

        //  The time point at which this event occurred.
        public ulong timestamp;
        //  The id and label of this transition event.
        public TransitionMsg transition;
        //  The starting state from which this event transitioned.
        public StateMsg start_state;
        //  The end state of this transition event.
        public StateMsg goal_state;

        public TransitionEventMsg()
        {
            this.timestamp = 0;
            this.transition = new TransitionMsg();
            this.start_state = new StateMsg();
            this.goal_state = new StateMsg();
        }

        public TransitionEventMsg(ulong timestamp, TransitionMsg transition, StateMsg start_state, StateMsg goal_state)
        {
            this.timestamp = timestamp;
            this.transition = transition;
            this.start_state = start_state;
            this.goal_state = goal_state;
        }

        public static TransitionEventMsg Deserialize(MessageDeserializer deserializer) => new TransitionEventMsg(deserializer);

        private TransitionEventMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.timestamp);
            this.transition = TransitionMsg.Deserialize(deserializer);
            this.start_state = StateMsg.Deserialize(deserializer);
            this.goal_state = StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.transition);
            serializer.Write(this.start_state);
            serializer.Write(this.goal_state);
        }

        public override string ToString()
        {
            return "TransitionEventMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\ntransition: " + transition.ToString() +
            "\nstart_state: " + start_state.ToString() +
            "\ngoal_state: " + goal_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
