//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ChainConnectionMsg : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ChainConnection";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        //  name of controller exporting reference_interfaces
        public string[] reference_interfaces;
        //  list of reference exported by controller

        public ChainConnectionMsg()
        {
            this.name = "";
            this.reference_interfaces = new string[0];
        }

        public ChainConnectionMsg(string name, string[] reference_interfaces)
        {
            this.name = name;
            this.reference_interfaces = reference_interfaces;
        }

        public static ChainConnectionMsg Deserialize(MessageDeserializer deserializer) => new ChainConnectionMsg(deserializer);

        private ChainConnectionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.reference_interfaces, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.WriteLength(this.reference_interfaces);
            serializer.Write(this.reference_interfaces);
        }

        public override string ToString()
        {
            return "ChainConnectionMsg: " +
            "\nname: " + name.ToString() +
            "\nreference_interfaces: " + System.String.Join(", ", reference_interfaces.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
