//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ControllerManagerActivityMsg : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ControllerManagerActivity";
        public override string RosMessageName => k_RosMessageName;

        //  This message is used to provide the activity within the controller manager regarding the change in state of controllers and hardware interfaces
        //  The header is used to provide timestamp information
        public Std.HeaderMsg header;
        //  The current state of the controllers
        public NamedLifecycleStateMsg[] controllers;
        //  The current state of the hardware components
        public NamedLifecycleStateMsg[] hardware_components;

        public ControllerManagerActivityMsg()
        {
            this.header = new Std.HeaderMsg();
            this.controllers = new NamedLifecycleStateMsg[0];
            this.hardware_components = new NamedLifecycleStateMsg[0];
        }

        public ControllerManagerActivityMsg(Std.HeaderMsg header, NamedLifecycleStateMsg[] controllers, NamedLifecycleStateMsg[] hardware_components)
        {
            this.header = header;
            this.controllers = controllers;
            this.hardware_components = hardware_components;
        }

        public static ControllerManagerActivityMsg Deserialize(MessageDeserializer deserializer) => new ControllerManagerActivityMsg(deserializer);

        private ControllerManagerActivityMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.controllers, NamedLifecycleStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.hardware_components, NamedLifecycleStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.controllers);
            serializer.Write(this.controllers);
            serializer.WriteLength(this.hardware_components);
            serializer.Write(this.hardware_components);
        }

        public override string ToString()
        {
            return "ControllerManagerActivityMsg: " +
            "\nheader: " + header.ToString() +
            "\ncontrollers: " + System.String.Join(", ", controllers.ToList()) +
            "\nhardware_components: " + System.String.Join(", ", hardware_components.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
