//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ControllerStateMsg : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ControllerState";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        //  controller name
        public string state;
        //  controller state: unconfigured, inactive, active, or finalized
        public string type;
        //  the controller class name, e.g. joint_trajectory_controller/JointTrajectoryController
        public bool is_async;
        //  true, if controller runs asynchronously. false, if controller runs synchronously
        public ushort update_rate;
        //  update rate of the controller in Hz
        public string[] claimed_interfaces;
        //  command interfaces currently owned by controller
        public string[] required_command_interfaces;
        //  command interfaces required by controller
        public string[] required_state_interfaces;
        //  state interfaces required by controller
        public bool is_chainable;
        //  specifies whether or not controller can export references for a controller chain
        public bool is_chained;
        //  specifies whether or not controller's exported references are claimed by another controller
        public string[] exported_state_interfaces;
        //  state interfaces to be exported (only applicable if is_chainable is true)
        public string[] reference_interfaces;
        //  references to be exported (only applicable if is_chainable is true)
        public ChainConnectionMsg[] chain_connections;
        //  specifies list of controllers and their exported references that the controller is chained to

        public ControllerStateMsg()
        {
            this.name = "";
            this.state = "";
            this.type = "";
            this.is_async = false;
            this.update_rate = 0;
            this.claimed_interfaces = new string[0];
            this.required_command_interfaces = new string[0];
            this.required_state_interfaces = new string[0];
            this.is_chainable = false;
            this.is_chained = false;
            this.exported_state_interfaces = new string[0];
            this.reference_interfaces = new string[0];
            this.chain_connections = new ChainConnectionMsg[0];
        }

        public ControllerStateMsg(string name, string state, string type, bool is_async, ushort update_rate, string[] claimed_interfaces, string[] required_command_interfaces, string[] required_state_interfaces, bool is_chainable, bool is_chained, string[] exported_state_interfaces, string[] reference_interfaces, ChainConnectionMsg[] chain_connections)
        {
            this.name = name;
            this.state = state;
            this.type = type;
            this.is_async = is_async;
            this.update_rate = update_rate;
            this.claimed_interfaces = claimed_interfaces;
            this.required_command_interfaces = required_command_interfaces;
            this.required_state_interfaces = required_state_interfaces;
            this.is_chainable = is_chainable;
            this.is_chained = is_chained;
            this.exported_state_interfaces = exported_state_interfaces;
            this.reference_interfaces = reference_interfaces;
            this.chain_connections = chain_connections;
        }

        public static ControllerStateMsg Deserialize(MessageDeserializer deserializer) => new ControllerStateMsg(deserializer);

        private ControllerStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.state);
            deserializer.Read(out this.type);
            deserializer.Read(out this.is_async);
            deserializer.Read(out this.update_rate);
            deserializer.Read(out this.claimed_interfaces, deserializer.ReadLength());
            deserializer.Read(out this.required_command_interfaces, deserializer.ReadLength());
            deserializer.Read(out this.required_state_interfaces, deserializer.ReadLength());
            deserializer.Read(out this.is_chainable);
            deserializer.Read(out this.is_chained);
            deserializer.Read(out this.exported_state_interfaces, deserializer.ReadLength());
            deserializer.Read(out this.reference_interfaces, deserializer.ReadLength());
            deserializer.Read(out this.chain_connections, ChainConnectionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.state);
            serializer.Write(this.type);
            serializer.Write(this.is_async);
            serializer.Write(this.update_rate);
            serializer.WriteLength(this.claimed_interfaces);
            serializer.Write(this.claimed_interfaces);
            serializer.WriteLength(this.required_command_interfaces);
            serializer.Write(this.required_command_interfaces);
            serializer.WriteLength(this.required_state_interfaces);
            serializer.Write(this.required_state_interfaces);
            serializer.Write(this.is_chainable);
            serializer.Write(this.is_chained);
            serializer.WriteLength(this.exported_state_interfaces);
            serializer.Write(this.exported_state_interfaces);
            serializer.WriteLength(this.reference_interfaces);
            serializer.Write(this.reference_interfaces);
            serializer.WriteLength(this.chain_connections);
            serializer.Write(this.chain_connections);
        }

        public override string ToString()
        {
            return "ControllerStateMsg: " +
            "\nname: " + name.ToString() +
            "\nstate: " + state.ToString() +
            "\ntype: " + type.ToString() +
            "\nis_async: " + is_async.ToString() +
            "\nupdate_rate: " + update_rate.ToString() +
            "\nclaimed_interfaces: " + System.String.Join(", ", claimed_interfaces.ToList()) +
            "\nrequired_command_interfaces: " + System.String.Join(", ", required_command_interfaces.ToList()) +
            "\nrequired_state_interfaces: " + System.String.Join(", ", required_state_interfaces.ToList()) +
            "\nis_chainable: " + is_chainable.ToString() +
            "\nis_chained: " + is_chained.ToString() +
            "\nexported_state_interfaces: " + System.String.Join(", ", exported_state_interfaces.ToList()) +
            "\nreference_interfaces: " + System.String.Join(", ", reference_interfaces.ToList()) +
            "\nchain_connections: " + System.String.Join(", ", chain_connections.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
