//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class HardwareInterfaceMsg : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/HardwareInterface";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string data_type;
        public bool is_available;
        public bool is_claimed;

        public HardwareInterfaceMsg()
        {
            this.name = "";
            this.data_type = "";
            this.is_available = false;
            this.is_claimed = false;
        }

        public HardwareInterfaceMsg(string name, string data_type, bool is_available, bool is_claimed)
        {
            this.name = name;
            this.data_type = data_type;
            this.is_available = is_available;
            this.is_claimed = is_claimed;
        }

        public static HardwareInterfaceMsg Deserialize(MessageDeserializer deserializer) => new HardwareInterfaceMsg(deserializer);

        private HardwareInterfaceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.data_type);
            deserializer.Read(out this.is_available);
            deserializer.Read(out this.is_claimed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.data_type);
            serializer.Write(this.is_available);
            serializer.Write(this.is_claimed);
        }

        public override string ToString()
        {
            return "HardwareInterfaceMsg: " +
            "\nname: " + name.ToString() +
            "\ndata_type: " + data_type.ToString() +
            "\nis_available: " + is_available.ToString() +
            "\nis_claimed: " + is_claimed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
