//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class HardwareComponentStateMsg : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/HardwareComponentState";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        //  Name of the hardware component
        public string type;
        //  Type of the hardware component
        public bool is_async;
        //  If the hardware component is running asynchronously
        public ushort rw_rate;
        //  read/write rate of the hardware component in Hz
        public string class_type;
        //  DEPRECATED
        public string plugin_name;
        //  The name of the plugin that is used to load the hardware component
        public Lifecycle.StateMsg state;
        //  State of the hardware component
        public HardwareInterfaceMsg[] command_interfaces;
        //  Command interfaces of the hardware component
        public HardwareInterfaceMsg[] state_interfaces;
        //  State interfaces of the hardware component

        public HardwareComponentStateMsg()
        {
            this.name = "";
            this.type = "";
            this.is_async = false;
            this.rw_rate = 0;
            this.class_type = "";
            this.plugin_name = "";
            this.state = new Lifecycle.StateMsg();
            this.command_interfaces = new HardwareInterfaceMsg[0];
            this.state_interfaces = new HardwareInterfaceMsg[0];
        }

        public HardwareComponentStateMsg(string name, string type, bool is_async, ushort rw_rate, string class_type, string plugin_name, Lifecycle.StateMsg state, HardwareInterfaceMsg[] command_interfaces, HardwareInterfaceMsg[] state_interfaces)
        {
            this.name = name;
            this.type = type;
            this.is_async = is_async;
            this.rw_rate = rw_rate;
            this.class_type = class_type;
            this.plugin_name = plugin_name;
            this.state = state;
            this.command_interfaces = command_interfaces;
            this.state_interfaces = state_interfaces;
        }

        public static HardwareComponentStateMsg Deserialize(MessageDeserializer deserializer) => new HardwareComponentStateMsg(deserializer);

        private HardwareComponentStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
            deserializer.Read(out this.is_async);
            deserializer.Read(out this.rw_rate);
            deserializer.Read(out this.class_type);
            deserializer.Read(out this.plugin_name);
            this.state = Lifecycle.StateMsg.Deserialize(deserializer);
            deserializer.Read(out this.command_interfaces, HardwareInterfaceMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.state_interfaces, HardwareInterfaceMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.type);
            serializer.Write(this.is_async);
            serializer.Write(this.rw_rate);
            serializer.Write(this.class_type);
            serializer.Write(this.plugin_name);
            serializer.Write(this.state);
            serializer.WriteLength(this.command_interfaces);
            serializer.Write(this.command_interfaces);
            serializer.WriteLength(this.state_interfaces);
            serializer.Write(this.state_interfaces);
        }

        public override string ToString()
        {
            return "HardwareComponentStateMsg: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\nis_async: " + is_async.ToString() +
            "\nrw_rate: " + rw_rate.ToString() +
            "\nclass_type: " + class_type.ToString() +
            "\nplugin_name: " + plugin_name.ToString() +
            "\nstate: " + state.ToString() +
            "\ncommand_interfaces: " + System.String.Join(", ", command_interfaces.ToList()) +
            "\nstate_interfaces: " + System.String.Join(", ", state_interfaces.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
