//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class NamedLifecycleStateMsg : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/NamedLifecycleState";
        public override string RosMessageName => k_RosMessageName;

        //  This message is used to provide information about the lifecycle state of the controller or the hardware components
        //  The name of the controller or hardware interface
        public string name;
        //  The current lifecycle state of the controller or hardware components
        public Lifecycle.StateMsg state;

        public NamedLifecycleStateMsg()
        {
            this.name = "";
            this.state = new Lifecycle.StateMsg();
        }

        public NamedLifecycleStateMsg(string name, Lifecycle.StateMsg state)
        {
            this.name = name;
            this.state = state;
        }

        public static NamedLifecycleStateMsg Deserialize(MessageDeserializer deserializer) => new NamedLifecycleStateMsg(deserializer);

        private NamedLifecycleStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.state = Lifecycle.StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "NamedLifecycleStateMsg: " +
            "\nname: " + name.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
