//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class ExecuteMotionPrimitiveSequenceFeedback : Message
    {
        public const string k_RosMessageName = "control_msgs/ExecuteMotionPrimitiveSequence";
        public override string RosMessageName => k_RosMessageName;

        //  Index of the currently executed motion primitive in the sequence.
        public byte current_primitive_index;

        public ExecuteMotionPrimitiveSequenceFeedback()
        {
            this.current_primitive_index = 0;
        }

        public ExecuteMotionPrimitiveSequenceFeedback(byte current_primitive_index)
        {
            this.current_primitive_index = current_primitive_index;
        }

        public static ExecuteMotionPrimitiveSequenceFeedback Deserialize(MessageDeserializer deserializer) => new ExecuteMotionPrimitiveSequenceFeedback(deserializer);

        private ExecuteMotionPrimitiveSequenceFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_primitive_index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_primitive_index);
        }

        public override string ToString()
        {
            return "ExecuteMotionPrimitiveSequenceFeedback: " +
            "\ncurrent_primitive_index: " + current_primitive_index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
