//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class ExecuteMotionPrimitiveSequenceGoal : Message
    {
        public const string k_RosMessageName = "control_msgs/ExecuteMotionPrimitiveSequence";
        public override string RosMessageName => k_RosMessageName;

        //  A list of MotionPrimitive messages that are executed in sequence. They don't have to be of the
        //  same type, as long as the robot supports executing them one after another.
        public MotionPrimitiveSequenceMsg trajectory;

        public ExecuteMotionPrimitiveSequenceGoal()
        {
            this.trajectory = new MotionPrimitiveSequenceMsg();
        }

        public ExecuteMotionPrimitiveSequenceGoal(MotionPrimitiveSequenceMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static ExecuteMotionPrimitiveSequenceGoal Deserialize(MessageDeserializer deserializer) => new ExecuteMotionPrimitiveSequenceGoal(deserializer);

        private ExecuteMotionPrimitiveSequenceGoal(MessageDeserializer deserializer)
        {
            this.trajectory = MotionPrimitiveSequenceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "ExecuteMotionPrimitiveSequenceGoal: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
