//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class ExecuteMotionPrimitiveSequenceResult : Message
    {
        public const string k_RosMessageName = "control_msgs/ExecuteMotionPrimitiveSequence";
        public override string RosMessageName => k_RosMessageName;

        public const int SUCCESSFUL = 0;
        public const int INVALID_GOAL = -1;
        public const int OLD_HEADER_TIMESTAMP = -3;
        public int error_code;
        public string error_string;

        public ExecuteMotionPrimitiveSequenceResult()
        {
            this.error_code = 0;
            this.error_string = "";
        }

        public ExecuteMotionPrimitiveSequenceResult(int error_code, string error_string)
        {
            this.error_code = error_code;
            this.error_string = error_string;
        }

        public static ExecuteMotionPrimitiveSequenceResult Deserialize(MessageDeserializer deserializer) => new ExecuteMotionPrimitiveSequenceResult(deserializer);

        private ExecuteMotionPrimitiveSequenceResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.error_code);
            deserializer.Read(out this.error_string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
            serializer.Write(this.error_string);
        }

        public override string ToString()
        {
            return "ExecuteMotionPrimitiveSequenceResult: " +
            "\nerror_code: " + error_code.ToString() +
            "\nerror_string: " + error_string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
