//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ConfigureControllerRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ConfigureController";
        public override string RosMessageName => k_RosMessageName;

        //  The ConfigureController service allows you to configure a single controller
        //  inside controller_manager
        //  To configure a controller, specify the "name" of the controller.
        //  The return value "ok" indicates if the controller was successfully
        //  configured or not.
        public string name;

        public ConfigureControllerRequest()
        {
            this.name = "";
        }

        public ConfigureControllerRequest(string name)
        {
            this.name = name;
        }

        public static ConfigureControllerRequest Deserialize(MessageDeserializer deserializer) => new ConfigureControllerRequest(deserializer);

        private ConfigureControllerRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "ConfigureControllerRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
