//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListControllersResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListControllers";
        public override string RosMessageName => k_RosMessageName;

        public ControllerStateMsg[] controller;

        public ListControllersResponse()
        {
            this.controller = new ControllerStateMsg[0];
        }

        public ListControllersResponse(ControllerStateMsg[] controller)
        {
            this.controller = controller;
        }

        public static ListControllersResponse Deserialize(MessageDeserializer deserializer) => new ListControllersResponse(deserializer);

        private ListControllersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.controller, ControllerStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.controller);
            serializer.Write(this.controller);
        }

        public override string ToString()
        {
            return "ListControllersResponse: " +
            "\ncontroller: " + System.String.Join(", ", controller.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
