//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListControllerTypesResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListControllerTypes";
        public override string RosMessageName => k_RosMessageName;

        public string[] types;
        public string[] base_classes;

        public ListControllerTypesResponse()
        {
            this.types = new string[0];
            this.base_classes = new string[0];
        }

        public ListControllerTypesResponse(string[] types, string[] base_classes)
        {
            this.types = types;
            this.base_classes = base_classes;
        }

        public static ListControllerTypesResponse Deserialize(MessageDeserializer deserializer) => new ListControllerTypesResponse(deserializer);

        private ListControllerTypesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.types, deserializer.ReadLength());
            deserializer.Read(out this.base_classes, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.types);
            serializer.Write(this.types);
            serializer.WriteLength(this.base_classes);
            serializer.Write(this.base_classes);
        }

        public override string ToString()
        {
            return "ListControllerTypesResponse: " +
            "\ntypes: " + System.String.Join(", ", types.ToList()) +
            "\nbase_classes: " + System.String.Join(", ", base_classes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
