//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListControllerTypesRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListControllerTypes";
        public override string RosMessageName => k_RosMessageName;

        //  The ListControllers service returns a list of controller types that are known
        //  to the controller manager plugin mechanism.

        public ListControllerTypesRequest()
        {
        }
        public static ListControllerTypesRequest Deserialize(MessageDeserializer deserializer) => new ListControllerTypesRequest(deserializer);

        private ListControllerTypesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ListControllerTypesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
