//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListHardwareInterfacesResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListHardwareInterfaces";
        public override string RosMessageName => k_RosMessageName;

        public HardwareInterfaceMsg[] command_interfaces;
        public HardwareInterfaceMsg[] state_interfaces;

        public ListHardwareInterfacesResponse()
        {
            this.command_interfaces = new HardwareInterfaceMsg[0];
            this.state_interfaces = new HardwareInterfaceMsg[0];
        }

        public ListHardwareInterfacesResponse(HardwareInterfaceMsg[] command_interfaces, HardwareInterfaceMsg[] state_interfaces)
        {
            this.command_interfaces = command_interfaces;
            this.state_interfaces = state_interfaces;
        }

        public static ListHardwareInterfacesResponse Deserialize(MessageDeserializer deserializer) => new ListHardwareInterfacesResponse(deserializer);

        private ListHardwareInterfacesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command_interfaces, HardwareInterfaceMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.state_interfaces, HardwareInterfaceMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.command_interfaces);
            serializer.Write(this.command_interfaces);
            serializer.WriteLength(this.state_interfaces);
            serializer.Write(this.state_interfaces);
        }

        public override string ToString()
        {
            return "ListHardwareInterfacesResponse: " +
            "\ncommand_interfaces: " + System.String.Join(", ", command_interfaces.ToList()) +
            "\nstate_interfaces: " + System.String.Join(", ", state_interfaces.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
