//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListHardwareInterfacesRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListHardwareInterfaces";
        public override string RosMessageName => k_RosMessageName;


        public ListHardwareInterfacesRequest()
        {
        }
        public static ListHardwareInterfacesRequest Deserialize(MessageDeserializer deserializer) => new ListHardwareInterfacesRequest(deserializer);

        private ListHardwareInterfacesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ListHardwareInterfacesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
