//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListHardwareComponentsRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListHardwareComponents";
        public override string RosMessageName => k_RosMessageName;

        //  The ListHardwareComponents service returns a list of hardware HardwareComponentsState.
        //  This will convey name, component_type, state and type of the components
        //  that are loaded inside the resource_manager.

        public ListHardwareComponentsRequest()
        {
        }
        public static ListHardwareComponentsRequest Deserialize(MessageDeserializer deserializer) => new ListHardwareComponentsRequest(deserializer);

        private ListHardwareComponentsRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ListHardwareComponentsRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
