//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListHardwareComponentsResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListHardwareComponents";
        public override string RosMessageName => k_RosMessageName;

        public HardwareComponentStateMsg[] component;

        public ListHardwareComponentsResponse()
        {
            this.component = new HardwareComponentStateMsg[0];
        }

        public ListHardwareComponentsResponse(HardwareComponentStateMsg[] component)
        {
            this.component = component;
        }

        public static ListHardwareComponentsResponse Deserialize(MessageDeserializer deserializer) => new ListHardwareComponentsResponse(deserializer);

        private ListHardwareComponentsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.component, HardwareComponentStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.component);
            serializer.Write(this.component);
        }

        public override string ToString()
        {
            return "ListHardwareComponentsResponse: " +
            "\ncomponent: " + System.String.Join(", ", component.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
