//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ListControllersRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ListControllers";
        public override string RosMessageName => k_RosMessageName;

        //  The ListControllers service returns a list of controller names/states/types of the
        //  controllers that are loaded inside the controller_manager.

        public ListControllersRequest()
        {
        }
        public static ListControllersRequest Deserialize(MessageDeserializer deserializer) => new ListControllersRequest(deserializer);

        private ListControllersRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ListControllersRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
