//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class LoadControllerResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/LoadController";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public LoadControllerResponse()
        {
            this.ok = false;
        }

        public LoadControllerResponse(bool ok)
        {
            this.ok = ok;
        }

        public static LoadControllerResponse Deserialize(MessageDeserializer deserializer) => new LoadControllerResponse(deserializer);

        private LoadControllerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "LoadControllerResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
