//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class LoadControllerRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/LoadController";
        public override string RosMessageName => k_RosMessageName;

        //  The LoadController service allows you to load a single controller
        //  inside controller_manager
        //  To load a controller, specify the "name" of the controller.
        //  The return value "ok" indicates if the controller was successfully
        //  constructed and initialized or not.
        public string name;

        public LoadControllerRequest()
        {
            this.name = "";
        }

        public LoadControllerRequest(string name)
        {
            this.name = name;
        }

        public static LoadControllerRequest Deserialize(MessageDeserializer deserializer) => new LoadControllerRequest(deserializer);

        private LoadControllerRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "LoadControllerRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
