//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ReloadControllerLibrariesResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ReloadControllerLibraries";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public ReloadControllerLibrariesResponse()
        {
            this.ok = false;
        }

        public ReloadControllerLibrariesResponse(bool ok)
        {
            this.ok = ok;
        }

        public static ReloadControllerLibrariesResponse Deserialize(MessageDeserializer deserializer) => new ReloadControllerLibrariesResponse(deserializer);

        private ReloadControllerLibrariesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "ReloadControllerLibrariesResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
