//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class ReloadControllerLibrariesRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/ReloadControllerLibraries";
        public override string RosMessageName => k_RosMessageName;

        //  The ReloadControllerLibraries service will reload all controllers that are available in
        //  the system as plugins
        //  Reloading libraries only works if there are no controllers loaded. If there
        //  are still some controllers loaded, the reloading will fail.
        //  If this bool is set to true, all loaded controllers will get
        //  killed automatically, and the reloading can succeed.
        public bool force_kill;

        public ReloadControllerLibrariesRequest()
        {
            this.force_kill = false;
        }

        public ReloadControllerLibrariesRequest(bool force_kill)
        {
            this.force_kill = force_kill;
        }

        public static ReloadControllerLibrariesRequest Deserialize(MessageDeserializer deserializer) => new ReloadControllerLibrariesRequest(deserializer);

        private ReloadControllerLibrariesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.force_kill);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.force_kill);
        }

        public override string ToString()
        {
            return "ReloadControllerLibrariesRequest: " +
            "\nforce_kill: " + force_kill.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
