//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class SetHardwareComponentStateResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/SetHardwareComponentState";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        public Lifecycle.StateMsg state;

        public SetHardwareComponentStateResponse()
        {
            this.ok = false;
            this.state = new Lifecycle.StateMsg();
        }

        public SetHardwareComponentStateResponse(bool ok, Lifecycle.StateMsg state)
        {
            this.ok = ok;
            this.state = state;
        }

        public static SetHardwareComponentStateResponse Deserialize(MessageDeserializer deserializer) => new SetHardwareComponentStateResponse(deserializer);

        private SetHardwareComponentStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            this.state = Lifecycle.StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "SetHardwareComponentStateResponse: " +
            "\nok: " + ok.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
