//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class SetHardwareComponentStateRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/SetHardwareComponentState";
        public override string RosMessageName => k_RosMessageName;

        //  The SetHardwareComponentState service allows to control life-cycle of a single hardware component.
        //  Supported states are defined in the design document of LifecycleNodes available at:
        //  https://design.ros2.org/articles/node_lifecycle.html
        //  To control life-cycle of a hardware component, specify its "name" and "target_state".
        //  Target state may be defined by "id" using a constant from `lifecycle_msgs/msg/State` or a label
        //  using definitions from `hardware_interface/types/lifecycle_state_names.hpp` file.
        //  The return value "ok" indicates if the component has successfully changed its state to "target_state".
        //  The return value "state" returns current state of the hardware component.
        public string name;
        public Lifecycle.StateMsg target_state;

        public SetHardwareComponentStateRequest()
        {
            this.name = "";
            this.target_state = new Lifecycle.StateMsg();
        }

        public SetHardwareComponentStateRequest(string name, Lifecycle.StateMsg target_state)
        {
            this.name = name;
            this.target_state = target_state;
        }

        public static SetHardwareComponentStateRequest Deserialize(MessageDeserializer deserializer) => new SetHardwareComponentStateRequest(deserializer);

        private SetHardwareComponentStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.target_state = Lifecycle.StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.target_state);
        }

        public override string ToString()
        {
            return "SetHardwareComponentStateRequest: " +
            "\nname: " + name.ToString() +
            "\ntarget_state: " + target_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
