//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class SwitchControllerResponse : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/SwitchController";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        public string message;

        public SwitchControllerResponse()
        {
            this.ok = false;
            this.message = "";
        }

        public SwitchControllerResponse(bool ok, string message)
        {
            this.ok = ok;
            this.message = message;
        }

        public static SwitchControllerResponse Deserialize(MessageDeserializer deserializer) => new SwitchControllerResponse(deserializer);

        private SwitchControllerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SwitchControllerResponse: " +
            "\nok: " + ok.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
