//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class SwitchControllerRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/SwitchController";
        public override string RosMessageName => k_RosMessageName;

        //  The SwitchController service allows you to deactivate a number of controllers
        //  and activate a number of controllers, all in one single timestep of the
        //  controller manager's control loop.
        //  To switch controllers, specify
        //   * the list of controller names to activate,
        //   * the list of controller names to deactivate, and
        //   * the strictness (STRICT, BEST_EFFORT, AUTO, or FORCE_AUTO)
        //     * STRICT means that switching will fail if anything goes wrong (an invalid
        //       controller name, a controller that failed to activate, etc.).
        //     * BEST_EFFORT:
        //       Transitions are only triggered if the controller is not yet in the target state.
        //       If it is already in the target state, no error occurs.
        //       Returns 'false' if all controllers of 'activate_controllers' or 'deactivate_controllers' are not yet loaded or configured,
        //       or the pending transitions of all existing controllers of 'activate_controllers'
        //       or 'deactivate_controllers' fail.
        //       Returns 'true' otherwise.
        //     * AUTO means that the controller manager will automatically resolve the controller
        //       chain in order to activate and/or deactivate the specified controllers.
        //       This is useful in complex systems when you want all dependent controllers to start
        //       within the same update iteration.
        //     * FORCE_AUTO means that the controller manager will take all necessary steps to activate
        //       the specified controllers without requiring you to explicitly list the controllers
        //       to be deactivated. This is useful when the controller being activated depends on
        //       another unknown controller that is currently running. The controller manager will
        //       deactivate any controllers that block the activation of the requested controller,
        //       following the mutually exclusive joint interface switching principle. For example,
        //       to activate a controller that uses a joint's position interface, the controller manager
        //       will automatically deactivate any controllers that use conflicting interfaces for
        //       the same joint.
        //   * activate the controllers as soon as their hardware dependencies are ready, will
        //     wait for all interfaces to be ready otherwise
        //   * the timeout before aborting pending controllers. Zero for infinite
        //  The return value "ok" indicates if the controllers were switched
        //  successfully or not. The meaning of success depends on the
        //  specified strictness.
        //  The return value "message" provides some human-readable information.
        public string[] activate_controllers;
        public string[] deactivate_controllers;
        public int strictness;
        public const int BEST_EFFORT = 1;
        public const int STRICT = 2;
        public const int AUTO = 3;
        public const int FORCE_AUTO = 4;
        public bool activate_asap;
        public BuiltinInterfaces.DurationMsg timeout;

        public SwitchControllerRequest()
        {
            this.activate_controllers = new string[0];
            this.deactivate_controllers = new string[0];
            this.strictness = 0;
            this.activate_asap = false;
            this.timeout = new BuiltinInterfaces.DurationMsg();
        }

        public SwitchControllerRequest(string[] activate_controllers, string[] deactivate_controllers, int strictness, bool activate_asap, BuiltinInterfaces.DurationMsg timeout)
        {
            this.activate_controllers = activate_controllers;
            this.deactivate_controllers = deactivate_controllers;
            this.strictness = strictness;
            this.activate_asap = activate_asap;
            this.timeout = timeout;
        }

        public static SwitchControllerRequest Deserialize(MessageDeserializer deserializer) => new SwitchControllerRequest(deserializer);

        private SwitchControllerRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activate_controllers, deserializer.ReadLength());
            deserializer.Read(out this.deactivate_controllers, deserializer.ReadLength());
            deserializer.Read(out this.strictness);
            deserializer.Read(out this.activate_asap);
            this.timeout = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.activate_controllers);
            serializer.Write(this.activate_controllers);
            serializer.WriteLength(this.deactivate_controllers);
            serializer.Write(this.deactivate_controllers);
            serializer.Write(this.strictness);
            serializer.Write(this.activate_asap);
            serializer.Write(this.timeout);
        }

        public override string ToString()
        {
            return "SwitchControllerRequest: " +
            "\nactivate_controllers: " + System.String.Join(", ", activate_controllers.ToList()) +
            "\ndeactivate_controllers: " + System.String.Join(", ", deactivate_controllers.ToList()) +
            "\nstrictness: " + strictness.ToString() +
            "\nactivate_asap: " + activate_asap.ToString() +
            "\ntimeout: " + timeout.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
