//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ControllerManager
{
    [Serializable]
    public class UnloadControllerRequest : Message
    {
        public const string k_RosMessageName = "controller_manager_msgs/UnloadController";
        public override string RosMessageName => k_RosMessageName;

        //  The UnloadController service allows you to unload a single controller
        //  from controller_manager
        //  To unload a controller, specify the "name" of the controller.
        //  The return value "ok" indicates if the controller was successfully
        //  unloaded or not
        public string name;

        public UnloadControllerRequest()
        {
            this.name = "";
        }

        public UnloadControllerRequest(string name)
        {
            this.name = name;
        }

        public static UnloadControllerRequest Deserialize(MessageDeserializer deserializer) => new UnloadControllerRequest(deserializer);

        private UnloadControllerRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "UnloadControllerRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
